### ISSUE TITLE
To read PDF file and take Input from it Using OCR

### ISSUE THREAD

**Issue by NishanthkrishnaEos** [mabarroso/ocr#2]
I have tried it but i am getting empty in "ocr.text", I have tried all the three WeOCR Project, OCR Web Service and Free OCR Online web service but i am still not able to get the required result

I have added in gem file :gem "ocr", "~> 0.3.1"  , Also installed the gem.
within my controller method i have placed the code
ocr = OCR.use :free_ocr
ocr.username='nishanthkrishna@eossys.com'
ocr.password='feRm4kNP'
ocr.login ocr.username,ocr.password,true
ocr.file= '/var/www/scaled_scores/output.pdf'
ocr.format= :txt
ocr.recognize
logger.info "************_ERROR: #{ocr.error}" 
 logger.info "**_**********RESULT: #{ocr.text}"    

both error and result object are empty

**Comment by mabarroso** [comment]
Looks like a provider error. The problem has been reported to them.

Thanks you very much for your feedback.  I will tell you about this issue as soon as.

************_ERROR: (soap:Server) System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream)
   at ocr.Analyze(String username, Byte[] image) in d:\home\home\webtropy\www\ocr.webtropy.com\App_Code\ocr.cs:line 42
   --- End of inner exception stack trace ---
***_*********RESULT:

**Comment by mabarroso** [comment]
The provider service work fine.

This code works

require 'ocr'
ocr = OCR.use :free_ocr
ocr.file= './demo.png'
ocr.format= :txt
ocr.recognize
puts "************_ERROR: #{ocr.error}"
puts "**_**********RESULT: #{ocr.text}"

The result
************_ERROR: false
***_*********RESULT: a demo

The demo image used is http://www.casimages.es/i/121109100523939884.png

Please, check that you /var/www/scaled_scores/output.pdf file have a valid image format.

**Comment by NishanthkrishnaEos** [comment]
Is it working for PDF file also... it is still not working for pdf  to text can u please look at it

**Comment by NishanthkrishnaEos** [comment]
Below is the error when i run ocr.recognize

W, [2012-11-09T15:43:20.675312 #3689]  WARN -- : HTTPI executes HTTP POST using the net_http adapter
D, [2012-11-09T15:43:23.447394 #3689] DEBUG -- : SOAP response (status 500):
D, [2012-11-09T15:43:23.447493 #3689] DEBUG -- : <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">soap:Bodysoap:Fault<faultcode>soap:Server</faultcode><faultstring>System.Web.Services.Protocols.SoapException: Server was unable to process request. ---&gt; System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream)
   at ocr.Analyze(String username, Byte[] image) in d:\home\home\webtropy\www\ocr.webtropy.com\App_Code\ocr.cs:line 42
   --- End of inner exception stack trace ---</faultstring><detail />/soap:Fault/soap:Body/soap:Envelope

The code i used

require 'ocr'
ocr = OCR.use :free_ocr
ocr.file= '/var/www/scaled_scores/output.pdf'
ocr.format= :txt
ocr.recognize
ocr.text                                   # ocr.text reurns => nill
ocr.error

# ocr.error returns

=> #<Savon::SOAP::Fault: (soap:Server) System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream)
   at ocr.Analyze(String username, Byte[] image) in d:\home\home\webtropy\www\ocr.webtropy.com\App_Code\ocr.cs:line 42
   --- End of inner exception stack trace ---> 

Please do take a look at it

Regards
Nishanth

**Comment by mabarroso** [comment]
I am afraid that this service is only allowed to convert image files. The provider for :free_ocr is http://www.free-ocr.co.uk/. 

You can use :onlineocr provider (http://www.ocrwebservice.com/), but only support pdf for output.

Sorry, but at this moment no have implement service provider for input pdf format.

**Comment by NishanthkrishnaEos** [comment]
Sir my client requires input from pdf file, Hence i need output of the pdf content in an object (like ocr.text), In case if ocr gem does not do it could you please suggest any other gem or service provider , Extremely thank you for the assistance and your time.

Regards
Nishanth

**Comment by mabarroso** [comment]
The pdf-reader gem (http://github.com/yob/pdf-reader) could be usefull for you. It have a lot of use examples to extract the PDF data. 

If the PDF contain text in image format, you can use ocr gem to convert it to text after extract the image file from PDF document. 

OCR gem allows you to use diferents service provider to image to text conversion. The quality of the conversion depends of the provider selected to work for.

**Comment by NishanthkrishnaEos** [comment]
Thank you 

Regards
Nishanth
